### ISSUE TITLE
Release 24.0

### ISSUE THREAD

**Issue by seleznev** [gnome-integration-team/firefox-gnome#198]
> Firefox 24
> on Week of September 17, 2013

https://wiki.mozilla.org/Features/Release_Tracking#Firefox_24

---
## Roadmap
1. [x] Return usage svg icons by default (reference: #197, #196, #122, #186). But maybe with SVG-filter for :active state.
2. [x] Drop different style for windows in "inactive" state (:-moz-window-inactive, d76ae5c249833f0b1724b2a01d69b963003e0c4b).
3. [x] Improve MS Windows support (#122).

Please review this ideas. :)

---
- Alpha 1: [gnome-firefox-24.0a1.xpi](https://launchpad.net/gnome-integration/firefox-gnome/firefox-gnome-releases/+download/gnome-firefox-24.0a1.xpi) (`master` + `upgrade-to-24` + `drop-inactive`).
- Alpha 2: [gnome-firefox-24.0a2.xpi](https://launchpad.net/gnome-integration/firefox-gnome/firefox-gnome-releases/+download/gnome-firefox-24.0a2.xpi), [firefox-extension-gnome-theme-tweak-24.0a2.xpi](https://dl.dropboxusercontent.com/u/107670598/firefox-extension-gnome-theme-tweak/alpha/24.0a2/firefox-extension-gnome-theme-tweak-24.0a2.xpi).
- RC (== "final"?): gnome-firefox-24.0.xpi, [firefox-extension-gnome-theme-tweak-24.0.xpi](https://addons.mozilla.org/en-US/firefox/addon/gnome-theme-tweak/versions/?page=1#version-24.0).
